### ISSUE TITLE
Move design system from old gh-pages Jekyll app to new Ember app

### ISSUE THREAD

**Issue by cattsmall** [GoodForPoC/GoodForPoC#14]
Take the design system from the `gh-pages` branch and migrate it over to `develop`

**Specific steps to take**
- [x] Audit existing design system
- [x] Identify gaps in design system
- [x] Fill gaps with new styles
- [x] Create new files and CSS design system architecture in `develop`

**Comment by jalcine** [comment]
Can we move it to `develop` instead of `master`? The deploy pipeline would have every push (or release) to `master` be recognized as a release.

I _could_ do something else like a tag in the commit message, if that helps. Having `master` as a "sane" branch and `develop` as the "experimentation but stable-ish" branch gives a bit of a devops sanity :)

**Comment by cattsmall** [comment]
Makes sense to me! Let's do that.

**Comment by adekunleoduye** [comment]
Did a quick audit of the current design here: https://drive.google.com/open?id=0BxahUHAPr7W_NjRQdXlOcnJSRkk

CC: @almnt

**Comment by chadtomkiss** [comment]
@cattsmall @adekunleoduye @jalcine 

How do you feel about having a styleguide produced using something like:

- http://fbrctr.github.io
- https://fractal.build

There's also tools that will parse CSS to generate styleguides like:

- http://warpspire.com/kss/styleguides

Just thinking for contributors to easily build out pages using a collection of predefined components.

**Comment by chadtomkiss** [comment]
There's a full list of tools here: https://github.com/davidhund/styleguide-generators

Some are no longer maintained, but it's an extensive list so worth having a gander!

**Comment by adekunleoduye** [comment]
@chadtomkiss thanks for sending these! I usually build my own but these look very interesting. 

We should probably start thinking about this when we kickoff the implementation of the design system. If you have experience in some of them, what are the pros & cons between them?

**Comment by chadtomkiss** [comment]
I am not a front-ender, but I have worked on a project that used Fractal to build out the components.

Pros:

- Pretty straightforward to get set up.
- Define data to be used for the component using a YAML config
- Define multiple variants for a component (active, hover, success etc)
- Can build layouts that comprise of multiple components
- Each component has it's own Sass file, which you can use to build your `app.css` with Gulp etc.
- Can export as HTML to the public directory so that it's accessible online.

Cons:

- The templating language used in your app may differ from the one in Fractal and so copy/pasting the component without modification isn't possible. You can write your own renderer to ma

However, I would play around with a few of them and see how you like them. They certainly save a tonne of time and provide a really good reference for new contributors to build out pages.

**Comment by cattsmall** [comment]
Now that I've set up some basic CSS styles, the only remaining question IMO is: what, if any, basic styles are missing so we can move forward? We can always edit CSS later, so I'd love to close this soon.

**Comment by jalcine** [comment]
Perhaps things around form fields (inputs + textareas).

Outside of that, we _should_ be okay. Those bits seem a bit more than atomic CSS blocks though.

**Comment by adekunleoduye** [comment]
I think adding icons with the suggestion Jacky made about the form elements would be good next steps but those aren't necessary for right now.

**Comment by cattsmall** [comment]
@jalcine i already added CSS for inputs and textareas; see the `forms.scss` file. Do you mean something more specific?

Also, what icons @adekunleoduye?

**Comment by cattsmall** [comment]
Moving the icons stuff to a new issue and closing this one.
